### ISSUE TITLE
icon.ico not defined

### ISSUE THREAD

**Issue by codeperfectplus** [Spidy20/wikipedia_GUI#1]
```bash
Traceback (most recent call last):
  File "wp_GUI.py", line 15, in <module>
    windo.iconbitmap('./meta/icon.ico')
  File "/home/codeperfectplus/anaconda3/lib/python3.7/tkinter/__init__.py", line 1871, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "./meta/icon.ico" not defined
```

**Comment by ikrambenabdelouahab** [comment]
anyone got solution for this, yet ?

**Comment by Spidy20** [comment]
The reason for this error is, the ICON file is missing. You can put this line in the comment.
